<?php
return array(
    'HOME'=>'  Home',
    'TRAVEL'=>'  Travel',
    'CULTURE'=>'  Culture & Languages',
    'ART'=>'  Art',
    'ABOUT'=>'  About',
    'CONTACT'=>'  Contacts',
    'WELCOME'=>'Welcome   ',
    'LOGOUT'=>'  Logout',
    'LOGIN'=>'   Login',
    'REGISTER'=>'  Register',
    'REGISTER1'=>'  Register',
    'LOGIN1'=>'  Login',
    'LANGUAGESS'=>'  English',
    'SEARCH'=>'Search...',
    'FOLLOW_US'=>'FOLLOW US',
    'AMAZING1'=>'Amazing',
    'COUNTRY1'=>'Thailand',
    'DESCRIPTION1'=>'Discover all the beauty of The Kingdom of Smile.',
    'AMAZING2'=>'Charming',
    'COUNTRY2'=>'China',
    'DESCRIPTION2'=>'All history in one country.',
     'AMAZING3'=>'Undiscovered',
    'COUNTRY3'=>'Belarus',
    'DESCRIPTION3'=>'Enigma in the heart of Europe',
    'LINK1'=>' Culture',
    'LINK2'=>' Travel',
    'LINK3'=>' Art',
    'LINK4'=>' Games',
    'ALL_RIGHT_RESERVED'=>'Maksim Narushevich © 2016. All rights reserved',
    'ADMIN_PANEL'=>'Site Admin',
    'PUBLISHED_ON'=>'Published on  ',
    'RETURN_TO_ARTICLES'=>'Return to Articles',
    'WRITE_COMMENT'=>'Write a comment...',
    'YOUR_EMAIL'=>'Your e-mail adress',
    'POST_COMMENT'=>'Post comment',
    'CANCEL'=>'Cancel',
    'INSERT_YOUR_NAME'=>'Insert your name',
    'INSERT_YOUR_EMAIL'=>'Insert your email',
    'SEND_YOUR_MESSAGE'=>'Type your message',
    'ATTACH_YOUR_FILE'=>'Attach your file',
    'SEND_MAIL'=>'Send Mail',
    'ASIA'=>'Asia',
    'WESTEUROPE'=>'West Europe',
    'OTHERWORLD'=>'Other World',
    'LANGUAGES'=>'Languages',
    'TRADITIONS'=>'Culture & Traditions',
    'CINEMAMUSIC'=>'Cinema & Music',
    'GALLERY'=>'Gallery',
    'BOOKS'=>'Books',
    'WEBDESIGN'=>'Web Design',
    'GRAPHICDESIGN'=>'Graphic Design',
    'UPTODATES'=>'Up-to-Dates',
    'DESIGNED'=>'Designed by',
    'MAKSIM'=>'Maksim Narushevich',
    'MAKSIM2'=>'Maksim Narushevich',
    'BEGINNER'=>'Web designer and the main develover of this web project.',
    'SEND_YOUR_OP'=>'Send your opinions and ask your questions! Always feel free to contact. Open for collaboration and similar ideas for discovering this world!',
    'FREE_TO_CALL'=>'Feel free to call for collaboration issues, for exchanging ideas and for sharing your experience.',
    'SEND_YOUR_STORIES'=>'Send your stories and share your experience',
    'THIS_PROJECT'=>'This project was created in order to share experience to those who is just going to obtain it and in order to get experience from those who has already discovered that is still undiscovered by you.',
    'IMMERSEDEEPLY'=>'Immerse deeply in undiscovered world!',
    'NAME'=>'Name :',
    'SECONDNAME'=>'Surname :',
    'AGE'=>'Age :',
    'COUNTRY'=>'Country :',
    'CITY'=>'City :',
    'EMAIL'=>'Email :',
    'OUR_LANGUAGES'=>'Languages we speak',
    'SORRY'=>'Sorry, there is no any article here yet!',
    'TRAVEL_AROUND'=>'Travel around the world!',
    'TRAVEL_AROUND_1'=>'The world still has amazing and interesting places that worth to be seen. Discover new places Discovering World project, get to know more and find more information here about that places that you are planning to visit soon.',
    'CULTURE_AROUND'=>'Weekend Grand Buffet',
    'CULTURE_AROUND_1'=>'The world still has amazing and interesting places that worth to be seen. Discover new places Discovering World project, get to know more and find more information here about that places that you are planning to visit soon.',
    'ART_AROUND'=>'Weekend Grand Buffet',
    'ART_AROUND_1'=>'The world still has amazing and interesting places that worth to be seen. Discover new places Discovering World project, get to know more and find more information here about that places that you are planning to visit soon.',
    'TRAVEL_DESCRIPTION'=>'           Here will be some travel description',
    'TRAVEL_DESCRIPTION_2'=>'China, officially the People\'s Republic of China (PRC), is a sovereign state in East Asia. It is the world\'s most'
    . 'populous country, with a population of over 1.35 billion. The PRC is a one-party state governed by the Communist Party, with its seat of government in the capital city of Beijing.[15] It exercises jurisdiction over 22 provinces; five autonomous regions; '
    . 'four direct-controlled municipalities (Beijing, Tianjin, Shanghai and Chongqing); two mostly self-governing special administrative regions (Hong Kong and Macau); and claims sovereignty over Taiwan.',
    'CULTURE_DESCRIPTION'=>'           Here will be some travel description',
    'CULTURE_DESCRIPTION_2'=>'China, officially the People\'s Republic of China (PRC), is a sovereign state in East Asia. It is the world\'s most'
    . 'populous country, with a population of over 1.35 billion. The PRC is a one-party state governed by the Communist Party, with its seat of government in the capital city of Beijing.[15] It exercises jurisdiction over 22 provinces; five autonomous regions; '
    . 'four direct-controlled municipalities (Beijing, Tianjin, Shanghai and Chongqing); two mostly self-governing special administrative regions (Hong Kong and Macau); and claims sovereignty over Taiwan.',
    'TRAVEL_DESCRIPTION_1'=>'           Here will be some travel description',
    'GAME_DESCRIPTION_2'=>'Game №1 is guessing color Game that requares to guess what color has been chosen.Try to guess with less attempts', 
    'GAME_DESCRIPTION_3'=>'Try Game 1', 
    'GAME_DESCRIPTION_4'=>'Game №2 is the funny game that suggests you to find one additional smile in the scope of the same faces.
                    Try to be more attentive and spot the additioanl one. ', 
    'GAME_DESCRIPTION_5'=>'Try Game 2',
    'ALL_ARTICLE_UPDATES'=>'ALL ARTICLE UPDATES',
    'WECOUNTRY'=>'  West European Country',
    'WECOUNTRY_DESCRIPTION'=>'Belarus (Listeni/bɛləˈruːs/ bel-ə-rooss; Belarusian: Белару́сь, tr. Bielaruś, IPA: [bʲɛlaˈrusʲ]; Russian: Белоруссия, tr. Byelorussiya; IPA: [bʲɪloˈrussɪʲɐ]), officially the Republic of Belarus,'
    . ' is a landlocked country in Eastern Europe[8] bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest.Belarus (Listeni/bɛləˈruːs/ bel-ə-rooss; Belarusian: Белару́сь, tr. Bielaruś, IPA: [bʲɛlaˈrusʲ]; Russian: Белоруссия, tr. Byelorussiya; IPA: [bʲɪloˈrussɪʲɐ]),'
    . ' officially the Republic of Belarus, is a landlocked country in Eastern Europe[8] bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest. ',
    'FECOUNTRY'=>'  Far East Country',
    'FECOUNTRY_DESCRIPTION'=>'Belarus (Listeni/bɛləˈruːs/ bel-ə-rooss; Belarusian: Белару́сь, tr. Bielaruś, IPA: [bʲɛlaˈrusʲ]; Russian: Белоруссия, tr. Byelorussiya; IPA: [bʲɪloˈrussɪʲɐ]), officially the Republic of Belarus,'
    . ' is a landlocked country in Eastern Europe[8] bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest.Belarus (Listeni/bɛləˈruːs/ bel-ə-rooss; Belarusian: Белару́сь, tr. Bielaruś, IPA: [bʲɛlaˈrusʲ]; Russian: Белоруссия, tr. Byelorussiya; IPA: [bʲɪloˈrussɪʲɐ]),'
    . ' officially the Republic of Belarus, is a landlocked country in Eastern Europe[8] bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest. ',
    'FRANCE'=>'France',
    'FRCOUNTRY'=>'  West European Country',
    'FRCOUNTRY_DESCRIPTION'=>'Belarus (Listeni/bɛləˈruːs/ bel-ə-rooss; Belarusian: Белару́сь, tr. Bielaruś, IPA: [bʲɛlaˈrusʲ]; Russian: Белоруссия, tr. Byelorussiya; IPA: [bʲɪloˈrussɪʲɐ]), officially the Republic of Belarus,'
    . ' is a landlocked country in Eastern Europe[8] bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest.Belarus (Listeni/bɛləˈruːs/ bel-ə-rooss; Belarusian: Белару́сь, tr. Bielaruś, IPA: [bʲɛlaˈrusʲ]; Russian: Белоруссия, tr. Byelorussiya; IPA: [bʲɪloˈrussɪʲɐ]),'
    . ' officially the Republic of Belarus, is a landlocked country in Eastern Europe[8] bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest. ',
    'GERMANY'=>'Germany',
    'GRCOUNTRY'=>'  West European Country',
    'GRCOUNTRY_DESCRIPTION'=>'Belarus (Listeni/bɛləˈruːs/ bel-ə-rooss; Belarusian: Белару́сь, tr. Bielaruś, IPA: [bʲɛlaˈrusʲ]; Russian: Белоруссия, tr. Byelorussiya; IPA: [bʲɪloˈrussɪʲɐ]), officially the Republic of Belarus,'
    . ' is a landlocked country in Eastern Europe[8] bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest.Belarus (Listeni/bɛləˈruːs/ bel-ə-rooss; Belarusian: Белару́сь, tr. Bielaruś, IPA: [bʲɛlaˈrusʲ]; Russian: Белоруссия, tr. Byelorussiya; IPA: [bʲɪloˈrussɪʲɐ]),'
    . ' officially the Republic of Belarus, is a landlocked country in Eastern Europe[8] bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest. ',
    'DISCOVER'=>'Discover more',
    'ARTICLE_ARCHIVE'=>'Article Archive',
    'IN_ORDER_TO_VOTE'=>'In order to vote please ',
    'OR'=>' or ',
    'ON_WEB_SITE'=>' on Web Site',
    'IN_ORDER_TO_COMMENT'=>'In order to leave comments please ',
    'ABOUT1'=>'Discover new stories, new places and new emotions with',
    'ABOUT1_1'=>'every weeks articles updates!',
    'DISCOVERING_WORLD'=>' DiscoveringWorld\'s',
    'ABOUT2'=>'New travelling stories from the whole world in one place!',
    'ABOUT3'=>'Discovering traditions and languages! Sharing with new interesting facts and stories that can deeply immerse us in new culture!',
    'ABOUT4'=>'Stories about art and design. New trends in web and graphic design that allows constantly to be up-to-date.',
    'LOCATION_INFORMATION'=>'Location Information',
    'LOCATION_MAP'=>'Map of our Location',
    'CONTACT_DESCRIPTION'=>'  Discover new stories, new places and new emotions with MyProject every weeks articles updates!'
    . 'Discover new stories, new places and new emotions with MyProject every weeks articles updates! '
    . 'Discover new stories, new places and new emotions with MyProject every weeks articles updates!',
    'CLOSE'=>'Close',
    'PASS'=>'Password :',
    'BACK'=>'Go Back',
    'PIC'=>'Picture :',
    'MORE'=>'More',
    'NOTHING'=>'Nothing has found',
    'SEARCH1'=>'Search',
    'SEARCH'=>'Search Results',
    'VIKI'=>'Viki: Watch now all new asian dramas online',
    'LEARN_FRENCH'=>'Learn French Online',
    'LANGUAGES_LINKS'=>'LANGUAGE LEARNING LINKS',
    'DESIGN_LINKS'=>'Web design online links',
    'FILL_AREA'=>'Please fill this area',
    'NATIONAL_GEOGRAPHIC'=>'All latests articles from National Geographic',
    'TRAVEL_PLUS'=>'Travel+ ADVENTURE',
    'BELARUS_BY'=>'News and articles about Belarus on belarus.by website',
    'FRANCE_VOYAGE'=>'All that you want to know about France on France-voyage.com website'
    );
?>